# Generated by Django 5.2.8 on 2026-08-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('presupuesto_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presupuesto_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_inmueble', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Lote', 'Lote'), ('Comercial', 'Comercial'), ('Otro', 'Otro')], max_length=50)),
                ('zona_interes', models.CharField(max_length=150)),
                ('habitaciones', models.PositiveIntegerField()),
                ('banos', models.PositiveIntegerField(verbose_name='Baños')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_operacion', models.CharField(choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], max_length=20)),
                ('tipo_inmueble', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Lote', 'Lote'), ('Comercial', 'Comercial'), ('Otro', 'Otro')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='m²', max_digits=10)),
                ('habitaciones', models.PositiveIntegerField()),
                ('banos', models.PositiveIntegerField(verbose_name='Baños')),
                ('direccion', models.CharField(max_length=250)),
                ('zona', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservada', 'Reservada'), ('Vendida', 'Vendida')], default='Disponible', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp')], default='Email', max_length=20)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app2.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app2.propiedad')),
            ],
        ),
    ]
