# Generated by Django 5.2.8 on 2026-08-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_cliente_propiedad_notificacionmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
    ]
