# Generated by Django 5.2.8 on 2026-08-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_propiedadimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host_user', models.EmailField(help_text='Ej: tu-correo@gmail.com', max_length=250)),
                ('email_host_password', models.CharField(help_text='Contraseña de Aplicación (16 caracteres)', max_length=150)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
