# Generated by Django 5.2.8 on 2026-08-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_configuracioncorreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Ej: 573001234567 (Incluye código de país, sin espacios ni el signo +)', max_length=20),
        ),
    ]
