# Generated by Django 5.2.8 on 2026-08-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedadimagen',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='imagen_principal',
        ),
        migrations.AddField(
            model_name='propiedadimagen',
            name='es_portada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedadimagen',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
