# Generated by Django 5.2.8 on 2026-08-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cliente_propiedad_notificacionmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionmatch',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='notificacionmatch',
            name='propiedad',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='NotificacionMatch',
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
    ]
